Swift 3 Syntax for Multi-clause conditions
AliSoftware/alisoftware.github.io pull request #13
Opened 2016-10-14 15:26 UTC by frankieshakes

- Updated multi-clause conditions to use Swift 3 syntax
- Changed data.length to data.count for byte length example.

2016-10-14 15:43 UTC, AliSoftware commented
Cool, thx!

I think I'll start to use the [Swift 3.0](https://img.shields.io/badge/Swift-3.0-green.svg) badge on top of the articles which have been revised for Swift 3, so that people reading my old article will know which ones have been converted to new syntax and which ones haven't yet. Could you add that badge at the top?

Also as you suggested in the comment on my blog post, I think it's worth converting it to Swift 3 conventions as well (lowercase enums and so on).

2016-10-14 15:45 UTC, AliSoftware requested changes

2016-10-14 15:45 UTC, AliSoftware commented on _posts/2016-05-16-pattern-matching-4.md
> +We can combine the `if let case` with a comma (`,`) -- where each condition is separated by `,` -- to create a multi-clause condition:
Why the change from `case let` to `let case` here?

2016-10-14 18:26 UTC, frankieshakes commented on _posts/2016-05-16-pattern-matching-4.md
> +We can combine the `if let case` with a comma (`,`) -- where each condition is separated by `,` -- to create a multi-clause condition:
Ooops. That's my mistake. It's still `if case let` ;)

2016-10-17 08:46 UTC, AliSoftware approved these changes

2016-10-17 09:18 UTC, merged

2016-10-17 09:28 UTC, AliSoftware commented
Thanks again for porting these posts to Swift 3! 👍 👌